services:
  grima_php:
    build: .
    container_name: grima_php
    working_dir: /app
    environment:
      DATABASE_URL: sqlite:/app/grima.sql
    volumes:
      - ./:/app
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    secrets:
      - user_ssh_key
      - gitconfig
    networks:
      - proxy

  grima-nginx:
    image: nginx
    container_name: grima-nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grima-nginx.rule=Host(`grima.wrlc.localhost`)"
      - "traefik.http.routers.grima-nginx.tls=true"
      - "traefik.http.routers.grima-nginx.entrypoints=websecure"
    volumes:
      - ./:/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - grima_php
    networks:
      - proxy

secrets:
  user_ssh_key:
    file: ${USER_SSH_KEY}
  gitconfig:
    file: ${GITCONFIG}

networks:
  proxy:
    external: true